name = "MimiDICE2010"
uuid = "4f2c5d70-42a7-11e9-1de8-c370bd984083"
version = "0.1.2-DEV"

[deps]
Mimi = "e4e893b0-ee5e-52ea-8111-44b3bdec128c"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
Mimi = "0.9"
XLSX = "0.5.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"

[targets]
test = ["Test", "DataFrames", "CSVFiles"]
